name: Manual Update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,6,12,18 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download original JSON
        run: curl -s https://repos.gabrx.eu.org/nabzclan.json > original.json
      - name: Run converter
        run: python3 converter.py
      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git checkout -b temp-branch
          rm -f original.json
          git add nabzclan.feather.json
          if git diff --staged --quiet; then
            echo "Nenhuma mudança detectada. Saindo."
            git checkout main
            git branch -D temp-branch
            exit 0
          fi
          git commit -m "Manual update"
          git push origin temp-branch --force
          git checkout main
          git merge temp-branch --strategy-option theirs --no-edit
          git push origin main --force
          git branch -D temp-branch
